### ISSUE TITLE
Can't run in IIs 7.5.7600.16385 in Windows Server 2008 R2

### ISSUE THREAD

**Issue by pmout** [uwudamith/Dashboard#1]
When deploy to Windows Server 2008 and try to connect to Dashboard IIs pool stops with error.
Someone use Dashboard in those scenario?

**Comment by uwudamith** [comment]
What is the error you are getting?

**Comment by pmout** [comment]
Hi,

In IIS I get the erro: an unhandled microsoft .net framework exception
occurred in w3wp.exe [4036]

After debug IIS the error is "Access to the registry key 'Global' is
denied."

Do you try deploy to IIS 7 ?

Thanks

Pedro Moutinho

Pedro Moutinho.

**Comment by uwudamith** [comment]
Hi,

I haven't try on IIS 7. Make sure that you install the .net framework match with the project

**Comment by uwudamith** [comment]
Closing issue
